name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/node-docker-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before this one

    steps:
      - name: SSH to the server and deploy Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "65.108.37.107"
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling the latest Docker image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/node-docker-app:latest

            echo "Stopping and removing any existing container..."
            sudo docker stop node-docker-app || true
            sudo docker rm node-docker-app || true

            echo "Running the new container..."
            sudo docker run -d --name node-docker-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/node-docker-app:latest

            echo "Deployment complete. Verifying the container is running..."
            sudo docker ps | grep node-docker-app || echo "Container failed to start!"
